odom_frame: odom_gazebo
base_link_frame: chassis_link
world_frame: odom_gazebo

two_d_mode: true

frequency: 50
#(X,Y,Z,
#roll,pitch,yaw,
#X˙,Y˙,Z˙,
#roll˙,pitch˙,yaw˙,
#X¨,Y¨,Z¨)

odom0: odom
odom0_config: [false, false, false,
               false, false, false,
               true, true, false,
               false, false, true,
               false, false, false]
odom0_differential: false
odom0_queue_size: 10
